### ISSUE TITLE
Potential issues on phpBB 3.2

### ISSUE THREAD

**Issue by JoshyPHP** [MarkDHamill/smartfeed#2]
In phpBB 3.2, the posts' text is stored as XML. If you want to modify a post's HTML, it should be done *after* the post has been rendered with `generate_text_for_display()`.

In [this block](https://github.com/MarkDHamill/smartfeed/blob/2b5c294ad740c4ebaa514fa9d10d46e55b1262a6/controller/feed.php#L1069-L1085), `censor_text()` is run on the original XML before it is rendered to HTML.

In [this block](https://github.com/MarkDHamill/smartfeed/blob/2b5c294ad740c4ebaa514fa9d10d46e55b1262a6/controller/feed.php#L1324-L1340), both `censor_text()` and `create_attachment_markup()` are used on the XML. Those should be moved down after `generate_text_for_display()` has been run. Also, `generate_text_for_display()` already censors the HTML so you shouldn't have to run it manually beforehand.

This may be the cause of [this issue](https://www.phpbb.com/community/viewtopic.php?p=15029586#p15029586).

**Comment by SpIdErPiGgY1984** [comment]
Problem solved. Thank you! :)
https://www.phpbb.com/community/viewtopic.php?f=556&t=2474556#p15029846
