### ISSUE TITLE
phpBB 3.2 compliance

### ISSUE THREAD

**Issue by BmdOnline** [MarkDHamill/smartfeed#3]
Hi,
According to phpBB 3.2, you may change your template file `overall_header_navigation_prepend.html`

Now, you are using :
>     <li class="small-icon icon-smartfeed no-bulletin"><a href="{{ U_SMARTFEED_PAGE }}">{{ lang('SMARTFEED_PAGE') }}</a></li>

I think it would be better to use :
> 			<li data-last-responsive="true">
> 				<a href="{U_SMARTFEED_PAGE}" title="{L_SMARTFEED_PAGE}" role="menuitem">
> 					<i class="icon fa-rss fa-fw" aria-hidden="true"></i><span>{L_SMARTFEED_PAGE}</span>
> 				</a>
> 			</li>

This is same format as `navbar_header.html` and avoid `icon_mini_feed.gif` (you can remove it).
So, it works with all templates (using fontawesome).

**Comment by MarkDHamill** [comment]
You are quite right about this. With phpBB 3.2, FontAwesome is supported so this is a much better way to go. It will show up in the next version.

**Comment by MarkDHamill** [comment]
Fixed in version 3.2.10.
